set_property PACKAGE_PIN V17 [get_ports {B[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}] 
set_property PACKAGE_PIN V16 [get_ports {B[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}] 
set_property PACKAGE_PIN W16 [get_ports {B[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}] 
set_property PACKAGE_PIN W17 [get_ports {B[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}] 
set_property PACKAGE_PIN W2 [get_ports {A[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}] 
set_property PACKAGE_PIN U1 [get_ports {A[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}] 
set_property PACKAGE_PIN T1 [get_ports {A[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}] 
set_property PACKAGE_PIN R2 [get_ports {A[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}] 
set_property PACKAGE_PIN V13 [get_ports {reg_out[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[0]}] 
set_property PACKAGE_PIN V3 [get_ports {reg_out[1]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[1]}] 
set_property PACKAGE_PIN W3 [get_ports {reg_out[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[2]}] 
set_property PACKAGE_PIN U3 [get_ports {reg_out[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[3]}] 
set_property PACKAGE_PIN P3 [get_ports {reg_out[4]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[4]}] 
set_property PACKAGE_PIN N3 [get_ports {reg_out[5]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[5]}] 
set_property PACKAGE_PIN P1 [get_ports {reg_out[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[6]}] 
set_property PACKAGE_PIN L1 [get_ports {reg_out[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {reg_out[7]}] 
set_property PACKAGE_PIN T17 [get_ports reset] 
set_property IOSTANDARD LVCMOS33 [get_ports reset] 
set_property PACKAGE_PIN U18 [get_ports AC] 
set_property IOSTANDARD LVCMOS33 [get_ports AC] 
set_property PACKAGE_PIN W19 [get_ports Add] 
set_property IOSTANDARD LVCMOS33 [get_ports Add] 
set_property PACKAGE_PIN W5 [get_ports clock] 
set_property IOSTANDARD LVCMOS33 [get_ports clock] 

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design]
